### PR TITLE
Update to Ember 2.8

### PR DESCRIPTION
**Pull request by filipecrosk**
## Changes proposed in this pull request
- Updated Ember and Ember-data to the latest version, 2.8. 
- Replaced `contains` by `includes` to address a deprecation, http://emberjs.com/deprecations/v2.x/#toc_enumerable-contains
- I renamed this function `columnContains` to `columnIncludes` just to make more sense follow the same name.

### CODE REVIEW

**Comment by bcardarella** [comment]
Makes sense. I think updating the ember-cli side of things can be done too, but perhaps addressed in another PR

**Comment by filipecrosk** [comment]
So, should I just remove the ember-cli update from this PR?

**Comment by bcardarella** [comment]
@filipecrosk did you re-run the addon generator? Run: `ember init` after you have installed the newer version of `ember-cli`. This will re-run the addon generator and prompt you on each file where there are conflicts.

**Comment by filipecrosk** [comment]
@bcardarella Yes, I did. And just to make sure I did it again but now I downgraded ember-cli to 2.7 and tested it again. 
Basically, both 2.7 and 2.8 tried  to change the same files/lines.  But it's basically some previous changes made here. 
For example:
screenshot 2016-09-28 09 26 15

So I think it's everything ok. But will be happy to remove it if you prefer.

**Comment by bcardarella** [comment]
nope, this works. Thanks!

**Pull request merged**
