### PR TITLE
update to ember 2.18

### PR DESCRIPTION
**Pull request by clairton**
Update to ember 2.18

### CODE REVIEW

**Comment by clairton** [comment]
@bcardarella this is good to merge?

**Comment by clairton** [comment]
=)

**Comment by CassioFelippe** [comment]
Nice work @clairton.
Waiting for @bcardarella to merge it!

**Comment by marcelbraghini** [comment]
very good! @clairton

**Comment by guilhermezamoner** [comment]
Good job @clairton :thumbsup:

**Pull request merged**
